steps:
  # This step init go app use go install .
  - name: 'gcr.io/cloud-builders/go'
    id: Install app
    args: ['install', '.']
    env: ['PROJECT_ROOT=hello']
  # Build the module.
  - name: golang
    args: ['go', 'build', '.']
  # This step build the container images .
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Image
    args:
      - 'build'
      - '-t'
      - 'gcr.io/k8s-0529/hello-gin'
      - '.'
  # this step pushes the images to gcr
  # the PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by cloud build .
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Image
    args:
      - 'push'
      - 'gcr.io/k8s-0529/hello-gin'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Create k8s app
    args:
      - set
      - image
      - deplyment
      - 'deployment/my-deployment'
      - 'my-container=gcr.io/k8s-0529/hello-gin'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster-1'